name: Publish Package to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build --workspaces
      - run: npm publish --workspaces
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          automatic_release_tag: latest
